name: firebase_template_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.15.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  #asssets
  cupertino_icons: ^1.0.2
  google_fonts: ^2.1.0 #https://pub.dev/packages/google_fonts
  #json
  json_annotation: ^4.3.0 #https://pub.dev/packages/json_annotation
  #url
  url_launcher: ^6.0.15 #https://pub.dev/packages/url_launcher
  # 状態管理
  flutter_riverpod: ^1.0.3 #https://pub.dev/packages/riverpod
  #firebase
  firebase_core: ^1.10.6 #https://pub.dev/packages/firebase_core
  cloud_firestore: ^3.1.5 #https://pub.dev/packages/cloud_firestore
  firebase_auth: ^3.3.4 #https://pub.dev/packages/firebase_auth
  google_sign_in: ^5.2.1
  # firebase_crashlytics: ^2.2.3 #https://pub.dev/packages/firebase_crashlytics
  # version管理
  package_info_plus: ^1.3.0 #https://pub.dev/packages/package_info_plus
  version: ^2.0.0 #https://pub.dev/packages/version
  # iOS ATT
  app_tracking_transparency: ^2.0.2 #https://pub.dev/packages/app_tracking_transparency/install
  #widget
  flutter_progress_hud: ^2.0.0 #https://pub.dev/packages/flutter_progress_hud
  auto_size_text: ^3.0.0
  flutterfire_ui: ^0.3.0 #https://pub.dev/packages/flutterfire_ui

  # 翻訳
  intl: ^0.17.0 #https://pub.dev/packages/intl/install


dev_dependencies:
  integration_test:
    sdk: flutter
  flutter_test:
    sdk: flutter
  flutter_driver:
    sdk: flutter

  flutter_lints: ^1.0.0
  build_runner: any
  freezed: ^1.1.0 #https://pub.dev/packages/freezed
  json_serializable: any
  mockito: ^5.0.0 #https://pub.dev/packages/mockito
  dart_code_metrics: ^4.8.1 #https://pub.dev/packages/dart_code_metrics

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  uses-material-design: true